[package]
name = "pumpkinplus"
version = "0.0.3"
edition = "2024"
authors = ["Xodium"]
description = "Minecraft Pumpkin plugin that enhances the base gameplay"

[lib]
crate-type = ["cdylib"]

[dependencies]
pumpkin-plugin-api = "0.1.0-dev+26.2-26.45"
minimessage-rs = "0.1.5"
minimessage-rt-compat = { git = "https://github.com/Mettwasser/minimessage-rs" }
tracing = "0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
config = { version = "0.15", default-features = false, features = ["json"] }

[profile.release]
lto = true
strip = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
