//! Mirror of the API entity type enum.
//!
//! These names correspond to the Pumpkin plugin API's `EntityType` variants.
//! Use this enum for configuration fields that reference specific entity types.

use serde::{Deserialize, Serialize};
use std::fmt;

/// Mirror of the API entity type enum.
///
/// Covers all entity types exposed by the Pumpkin plugin API.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(rename_all = "PascalCase")]
pub enum EntityType {
    AcaciaBoat,
    AcaciaChestBoat,
    Allay,
    AreaEffectCloud,
    Armadillo,
    ArmorStand,
    Arrow,
    Axolotl,
    BambooChestRaft,
    BambooRaft,
    Bat,
    Bee,
    BirchBoat,
    BirchChestBoat,
    Blaze,
    BlockDisplay,
    Bogged,
    Breeze,
    BreezeWindCharge,
    Camel,
    CamelHusk,
    Cat,
    CaveSpider,
    CherryBoat,
    CherryChestBoat,
    ChestMinecart,
    Chicken,
    Cod,
    CommandBlockMinecart,
    CopperGolem,
    Cow,
    Creaking,
    Creeper,
    DarkOakBoat,
    DarkOakChestBoat,
    Dolphin,
    Donkey,
    DragonFireball,
    Drowned,
    Egg,
    ElderGuardian,
    EndCrystal,
    EnderDragon,
    Enderman,
    Endermite,
    EnderPearl,
    Evoker,
    EvokerFangs,
    ExperienceBottle,
    ExperienceOrb,
    EyeOfEnder,
    FallingBlock,
    Fireball,
    FireworkRocket,
    FishingBobber,
    Fox,
    Frog,
    FurnaceMinecart,
    Ghast,
    Giant,
    GlowItemFrame,
    GlowSquid,
    Goat,
    Guardian,
    HappyGhast,
    Hoglin,
    HopperMinecart,
    Horse,
    Husk,
    Illusioner,
    Interaction,
    IronGolem,
    Item,
    ItemDisplay,
    ItemFrame,
    JungleBoat,
    JungleChestBoat,
    LeashKnot,
    LightningBolt,
    LingeringPotion,
    Llama,
    LlamaSpit,
    MagmaCube,
    MangroveBoat,
    MangroveChestBoat,
    Mannequin,
    Marker,
    Minecart,
    Mooshroom,
    Mule,
    Nautilus,
    OakBoat,
    OakChestBoat,
    Ocelot,
    OminousItemSpawner,
    Painting,
    PaleOakBoat,
    PaleOakChestBoat,
    Panda,
    Parched,
    Parrot,
    Phantom,
    Pig,
    Piglin,
    PiglinBrute,
    Pillager,
    Player,
    PolarBear,
    Pufferfish,
    Rabbit,
    Ravager,
    Salmon,
    Sheep,
    Shulker,
    ShulkerBullet,
    Silverfish,
    Skeleton,
    SkeletonHorse,
    Slime,
    SmallFireball,
    Sniffer,
    Snowball,
    SnowGolem,
    SpawnerMinecart,
    SpectralArrow,
    Spider,
    SplashPotion,
    SpruceBoat,
    SpruceChestBoat,
    Squid,
    Stray,
    Strider,
    Tadpole,
    TextDisplay,
    Tnt,
    TntMinecart,
    TraderLlama,
    Trident,
    TropicalFish,
    Turtle,
    Vex,
    Villager,
    Vindicator,
    WanderingTrader,
    Warden,
    WindCharge,
    Witch,
    Wither,
    WitherSkeleton,
    WitherSkull,
    Wolf,
    Zoglin,
    Zombie,
    ZombieHorse,
    ZombieNautilus,
    ZombieVillager,
    ZombifiedPiglin,
}

impl EntityType {
    /// Returns true if the given list is empty (allow-all) or contains this entity type.
    pub fn matches_config(&self, allowed: &[Self]) -> bool {
        allowed.is_empty() || allowed.contains(self)
    }

    /// Convert from any type that implements `Debug` (such as the upstream API entity type).
    ///
    /// Uses the `Debug` representation as the canonical name, falling back
    /// to `Zombie` if the upstream type emits something unexpected.
    pub fn from_debug<T: std::fmt::Debug>(value: &T) -> Self {
        let repr = format!("{:?}", value);
        match repr.as_str() {
            "AcaciaBoat" => Self::AcaciaBoat,
            "AcaciaChestBoat" => Self::AcaciaChestBoat,
            "Allay" => Self::Allay,
            "AreaEffectCloud" => Self::AreaEffectCloud,
            "Armadillo" => Self::Armadillo,
            "ArmorStand" => Self::ArmorStand,
            "Arrow" => Self::Arrow,
            "Axolotl" => Self::Axolotl,
            "BambooChestRaft" => Self::BambooChestRaft,
            "BambooRaft" => Self::BambooRaft,
            "Bat" => Self::Bat,
            "Bee" => Self::Bee,
            "BirchBoat" => Self::BirchBoat,
            "BirchChestBoat" => Self::BirchChestBoat,
            "Blaze" => Self::Blaze,
            "BlockDisplay" => Self::BlockDisplay,
            "Bogged" => Self::Bogged,
            "Breeze" => Self::Breeze,
            "BreezeWindCharge" => Self::BreezeWindCharge,
            "Camel" => Self::Camel,
            "CamelHusk" => Self::CamelHusk,
            "Cat" => Self::Cat,
            "CaveSpider" => Self::CaveSpider,
            "CherryBoat" => Self::CherryBoat,
            "CherryChestBoat" => Self::CherryChestBoat,
            "ChestMinecart" => Self::ChestMinecart,
            "Chicken" => Self::Chicken,
            "Cod" => Self::Cod,
            "CommandBlockMinecart" => Self::CommandBlockMinecart,
            "CopperGolem" => Self::CopperGolem,
            "Cow" => Self::Cow,
            "Creaking" => Self::Creaking,
            "Creeper" => Self::Creeper,
            "DarkOakBoat" => Self::DarkOakBoat,
            "DarkOakChestBoat" => Self::DarkOakChestBoat,
            "Dolphin" => Self::Dolphin,
            "Donkey" => Self::Donkey,
            "DragonFireball" => Self::DragonFireball,
            "Drowned" => Self::Drowned,
            "Egg" => Self::Egg,
            "ElderGuardian" => Self::ElderGuardian,
            "EndCrystal" => Self::EndCrystal,
            "EnderDragon" => Self::EnderDragon,
            "Enderman" => Self::Enderman,
            "Endermite" => Self::Endermite,
            "EnderPearl" => Self::EnderPearl,
            "Evoker" => Self::Evoker,
            "EvokerFangs" => Self::EvokerFangs,
            "ExperienceBottle" => Self::ExperienceBottle,
            "ExperienceOrb" => Self::ExperienceOrb,
            "EyeOfEnder" => Self::EyeOfEnder,
            "FallingBlock" => Self::FallingBlock,
            "Fireball" => Self::Fireball,
            "FireworkRocket" => Self::FireworkRocket,
            "FishingBobber" => Self::FishingBobber,
            "Fox" => Self::Fox,
            "Frog" => Self::Frog,
            "FurnaceMinecart" => Self::FurnaceMinecart,
            "Ghast" => Self::Ghast,
            "Giant" => Self::Giant,
            "GlowItemFrame" => Self::GlowItemFrame,
            "GlowSquid" => Self::GlowSquid,
            "Goat" => Self::Goat,
            "Guardian" => Self::Guardian,
            "HappyGhast" => Self::HappyGhast,
            "Hoglin" => Self::Hoglin,
            "HopperMinecart" => Self::HopperMinecart,
            "Horse" => Self::Horse,
            "Husk" => Self::Husk,
            "Illusioner" => Self::Illusioner,
            "Interaction" => Self::Interaction,
            "IronGolem" => Self::IronGolem,
            "Item" => Self::Item,
            "ItemDisplay" => Self::ItemDisplay,
            "ItemFrame" => Self::ItemFrame,
            "JungleBoat" => Self::JungleBoat,
            "JungleChestBoat" => Self::JungleChestBoat,
            "LeashKnot" => Self::LeashKnot,
            "LightningBolt" => Self::LightningBolt,
            "LingeringPotion" => Self::LingeringPotion,
            "Llama" => Self::Llama,
            "LlamaSpit" => Self::LlamaSpit,
            "MagmaCube" => Self::MagmaCube,
            "MangroveBoat" => Self::MangroveBoat,
            "MangroveChestBoat" => Self::MangroveChestBoat,
            "Mannequin" => Self::Mannequin,
            "Marker" => Self::Marker,
            "Minecart" => Self::Minecart,
            "Mooshroom" => Self::Mooshroom,
            "Mule" => Self::Mule,
            "Nautilus" => Self::Nautilus,
            "OakBoat" => Self::OakBoat,
            "OakChestBoat" => Self::OakChestBoat,
            "Ocelot" => Self::Ocelot,
            "OminousItemSpawner" => Self::OminousItemSpawner,
            "Painting" => Self::Painting,
            "PaleOakBoat" => Self::PaleOakBoat,
            "PaleOakChestBoat" => Self::PaleOakChestBoat,
            "Panda" => Self::Panda,
            "Parched" => Self::Parched,
            "Parrot" => Self::Parrot,
            "Phantom" => Self::Phantom,
            "Pig" => Self::Pig,
            "Piglin" => Self::Piglin,
            "PiglinBrute" => Self::PiglinBrute,
            "Pillager" => Self::Pillager,
            "Player" => Self::Player,
            "PolarBear" => Self::PolarBear,
            "Pufferfish" => Self::Pufferfish,
            "Rabbit" => Self::Rabbit,
            "Ravager" => Self::Ravager,
            "Salmon" => Self::Salmon,
            "Sheep" => Self::Sheep,
            "Shulker" => Self::Shulker,
            "ShulkerBullet" => Self::ShulkerBullet,
            "Silverfish" => Self::Silverfish,
            "Skeleton" => Self::Skeleton,
            "SkeletonHorse" => Self::SkeletonHorse,
            "Slime" => Self::Slime,
            "SmallFireball" => Self::SmallFireball,
            "Sniffer" => Self::Sniffer,
            "Snowball" => Self::Snowball,
            "SnowGolem" => Self::SnowGolem,
            "SpawnerMinecart" => Self::SpawnerMinecart,
            "SpectralArrow" => Self::SpectralArrow,
            "Spider" => Self::Spider,
            "SplashPotion" => Self::SplashPotion,
            "SpruceBoat" => Self::SpruceBoat,
            "SpruceChestBoat" => Self::SpruceChestBoat,
            "Squid" => Self::Squid,
            "Stray" => Self::Stray,
            "Strider" => Self::Strider,
            "Tadpole" => Self::Tadpole,
            "TextDisplay" => Self::TextDisplay,
            "Tnt" => Self::Tnt,
            "TntMinecart" => Self::TntMinecart,
            "TraderLlama" => Self::TraderLlama,
            "Trident" => Self::Trident,
            "TropicalFish" => Self::TropicalFish,
            "Turtle" => Self::Turtle,
            "Vex" => Self::Vex,
            "Villager" => Self::Villager,
            "Vindicator" => Self::Vindicator,
            "WanderingTrader" => Self::WanderingTrader,
            "Warden" => Self::Warden,
            "WindCharge" => Self::WindCharge,
            "Witch" => Self::Witch,
            "Wither" => Self::Wither,
            "WitherSkeleton" => Self::WitherSkeleton,
            "WitherSkull" => Self::WitherSkull,
            "Wolf" => Self::Wolf,
            "Zoglin" => Self::Zoglin,
            "Zombie" => Self::Zombie,
            "ZombieHorse" => Self::ZombieHorse,
            "ZombieNautilus" => Self::ZombieNautilus,
            "ZombieVillager" => Self::ZombieVillager,
            "ZombifiedPiglin" => Self::ZombifiedPiglin,
            _ => Self::Zombie,
        }
    }
}

impl fmt::Display for EntityType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
