//! Mirror of the API entity type enum.
//!
//! These names correspond to the Pumpkin plugin API's `EntityType` variants.
//! Use this enum for configuration fields that reference specific entity types.

use serde::{Deserialize, Serialize};
use std::fmt;

/// Mirror of the API entity type enum.
///
/// Covers all entity types exposed by the Pumpkin plugin API.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(rename_all = "PascalCase")]
pub enum EntityType {
    AcaciaBoat,
    AcaciaChestBoat,
    Allay,
    AreaEffectCloud,
    Armadillo,
    ArmorStand,
    Arrow,
    Axolotl,
    BambooChestRaft,
    BambooRaft,
    Bat,
    Bee,
    BirchBoat,
    BirchChestBoat,
    Blaze,
    BlockDisplay,
    Bogged,
    Breeze,
    BreezeWindCharge,
    Camel,
    CamelHusk,
    Cat,
    CaveSpider,
    CherryBoat,
    CherryChestBoat,
    ChestMinecart,
    Chicken,
    Cod,
    CommandBlockMinecart,
    CopperGolem,
    Cow,
    Creaking,
    Creeper,
    DarkOakBoat,
    DarkOakChestBoat,
    Dolphin,
    Donkey,
    DragonFireball,
    Drowned,
    Egg,
    ElderGuardian,
    EndCrystal,
    EnderDragon,
    Enderman,
    Endermite,
    EnderPearl,
    Evoker,
    EvokerFangs,
    ExperienceBottle,
    ExperienceOrb,
    EyeOfEnder,
    FallingBlock,
    Fireball,
    FireworkRocket,
    FishingBobber,
    Fox,
    Frog,
    FurnaceMinecart,
    Ghast,
    Giant,
    GlowItemFrame,
    GlowSquid,
    Goat,
    Guardian,
    HappyGhast,
    Hoglin,
    HopperMinecart,
    Horse,
    Husk,
    Illusioner,
    Interaction,
    IronGolem,
    Item,
    ItemDisplay,
    ItemFrame,
    JungleBoat,
    JungleChestBoat,
    LeashKnot,
    LightningBolt,
    LingeringPotion,
    Llama,
    LlamaSpit,
    MagmaCube,
    MangroveBoat,
    MangroveChestBoat,
    Mannequin,
    Marker,
    Minecart,
    Mooshroom,
    Mule,
    Nautilus,
    OakBoat,
    OakChestBoat,
    Ocelot,
    OminousItemSpawner,
    Painting,
    PaleOakBoat,
    PaleOakChestBoat,
    Panda,
    Parched,
    Parrot,
    Phantom,
    Pig,
    Piglin,
    PiglinBrute,
    Pillager,
    Player,
    PolarBear,
    Pufferfish,
    Rabbit,
    Ravager,
    Salmon,
    Sheep,
    Shulker,
    ShulkerBullet,
    Silverfish,
    Skeleton,
    SkeletonHorse,
    Slime,
    SmallFireball,
    Sniffer,
    Snowball,
    SnowGolem,
    SpawnerMinecart,
    SpectralArrow,
    Spider,
    SplashPotion,
    SpruceBoat,
    SpruceChestBoat,
    Squid,
    Stray,
    Strider,
    Tadpole,
    TextDisplay,
    Tnt,
    TntMinecart,
    TraderLlama,
    Trident,
    TropicalFish,
    Turtle,
    Vex,
    Villager,
    Vindicator,
    WanderingTrader,
    Warden,
    WindCharge,
    Witch,
    Wither,
    WitherSkeleton,
    WitherSkull,
    Wolf,
    Zoglin,
    Zombie,
    ZombieHorse,
    ZombieNautilus,
    ZombieVillager,
    ZombifiedPiglin,
}

impl EntityType {
    /// Returns true if the given list is empty (allow-all) or contains this entity type.
    pub fn matches_config(&self, allowed: &[Self]) -> bool {
        allowed.is_empty() || allowed.contains(self)
    }
}

/// Convert from the upstream API `EntityType` to our mirror type.
///
/// Uses the debug representation as the canonical name, falling back
/// to `Zombie` if the upstream type emits something unexpected.
impl From<pumpkin_plugin_api::world::EntityType> for EntityType {
    fn from(value: pumpkin_plugin_api::world::EntityType) -> Self {
        #[allow(unreachable_patterns)]
        match value {
            pumpkin_plugin_api::world::EntityType::AcaciaBoat => Self::AcaciaBoat,
            pumpkin_plugin_api::world::EntityType::AcaciaChestBoat => Self::AcaciaChestBoat,
            pumpkin_plugin_api::world::EntityType::Allay => Self::Allay,
            pumpkin_plugin_api::world::EntityType::AreaEffectCloud => Self::AreaEffectCloud,
            pumpkin_plugin_api::world::EntityType::Armadillo => Self::Armadillo,
            pumpkin_plugin_api::world::EntityType::ArmorStand => Self::ArmorStand,
            pumpkin_plugin_api::world::EntityType::Arrow => Self::Arrow,
            pumpkin_plugin_api::world::EntityType::Axolotl => Self::Axolotl,
            pumpkin_plugin_api::world::EntityType::BambooChestRaft => Self::BambooChestRaft,
            pumpkin_plugin_api::world::EntityType::BambooRaft => Self::BambooRaft,
            pumpkin_plugin_api::world::EntityType::Bat => Self::Bat,
            pumpkin_plugin_api::world::EntityType::Bee => Self::Bee,
            pumpkin_plugin_api::world::EntityType::BirchBoat => Self::BirchBoat,
            pumpkin_plugin_api::world::EntityType::BirchChestBoat => Self::BirchChestBoat,
            pumpkin_plugin_api::world::EntityType::Blaze => Self::Blaze,
            pumpkin_plugin_api::world::EntityType::BlockDisplay => Self::BlockDisplay,
            pumpkin_plugin_api::world::EntityType::Bogged => Self::Bogged,
            pumpkin_plugin_api::world::EntityType::Breeze => Self::Breeze,
            pumpkin_plugin_api::world::EntityType::BreezeWindCharge => Self::BreezeWindCharge,
            pumpkin_plugin_api::world::EntityType::Camel => Self::Camel,
            pumpkin_plugin_api::world::EntityType::CamelHusk => Self::CamelHusk,
            pumpkin_plugin_api::world::EntityType::Cat => Self::Cat,
            pumpkin_plugin_api::world::EntityType::CaveSpider => Self::CaveSpider,
            pumpkin_plugin_api::world::EntityType::CherryBoat => Self::CherryBoat,
            pumpkin_plugin_api::world::EntityType::CherryChestBoat => Self::CherryChestBoat,
            pumpkin_plugin_api::world::EntityType::ChestMinecart => Self::ChestMinecart,
            pumpkin_plugin_api::world::EntityType::Chicken => Self::Chicken,
            pumpkin_plugin_api::world::EntityType::Cod => Self::Cod,
            pumpkin_plugin_api::world::EntityType::CommandBlockMinecart => {
                Self::CommandBlockMinecart
            }
            pumpkin_plugin_api::world::EntityType::CopperGolem => Self::CopperGolem,
            pumpkin_plugin_api::world::EntityType::Cow => Self::Cow,
            pumpkin_plugin_api::world::EntityType::Creaking => Self::Creaking,
            pumpkin_plugin_api::world::EntityType::Creeper => Self::Creeper,
            pumpkin_plugin_api::world::EntityType::DarkOakBoat => Self::DarkOakBoat,
            pumpkin_plugin_api::world::EntityType::DarkOakChestBoat => Self::DarkOakChestBoat,
            pumpkin_plugin_api::world::EntityType::Dolphin => Self::Dolphin,
            pumpkin_plugin_api::world::EntityType::Donkey => Self::Donkey,
            pumpkin_plugin_api::world::EntityType::DragonFireball => Self::DragonFireball,
            pumpkin_plugin_api::world::EntityType::Drowned => Self::Drowned,
            pumpkin_plugin_api::world::EntityType::Egg => Self::Egg,
            pumpkin_plugin_api::world::EntityType::ElderGuardian => Self::ElderGuardian,
            pumpkin_plugin_api::world::EntityType::EndCrystal => Self::EndCrystal,
            pumpkin_plugin_api::world::EntityType::EnderDragon => Self::EnderDragon,
            pumpkin_plugin_api::world::EntityType::Enderman => Self::Enderman,
            pumpkin_plugin_api::world::EntityType::Endermite => Self::Endermite,
            pumpkin_plugin_api::world::EntityType::EnderPearl => Self::EnderPearl,
            pumpkin_plugin_api::world::EntityType::Evoker => Self::Evoker,
            pumpkin_plugin_api::world::EntityType::EvokerFangs => Self::EvokerFangs,
            pumpkin_plugin_api::world::EntityType::ExperienceBottle => Self::ExperienceBottle,
            pumpkin_plugin_api::world::EntityType::ExperienceOrb => Self::ExperienceOrb,
            pumpkin_plugin_api::world::EntityType::EyeOfEnder => Self::EyeOfEnder,
            pumpkin_plugin_api::world::EntityType::FallingBlock => Self::FallingBlock,
            pumpkin_plugin_api::world::EntityType::Fireball => Self::Fireball,
            pumpkin_plugin_api::world::EntityType::FireworkRocket => Self::FireworkRocket,
            pumpkin_plugin_api::world::EntityType::FishingBobber => Self::FishingBobber,
            pumpkin_plugin_api::world::EntityType::Fox => Self::Fox,
            pumpkin_plugin_api::world::EntityType::Frog => Self::Frog,
            pumpkin_plugin_api::world::EntityType::FurnaceMinecart => Self::FurnaceMinecart,
            pumpkin_plugin_api::world::EntityType::Ghast => Self::Ghast,
            pumpkin_plugin_api::world::EntityType::Giant => Self::Giant,
            pumpkin_plugin_api::world::EntityType::GlowItemFrame => Self::GlowItemFrame,
            pumpkin_plugin_api::world::EntityType::GlowSquid => Self::GlowSquid,
            pumpkin_plugin_api::world::EntityType::Goat => Self::Goat,
            pumpkin_plugin_api::world::EntityType::Guardian => Self::Guardian,
            pumpkin_plugin_api::world::EntityType::HappyGhast => Self::HappyGhast,
            pumpkin_plugin_api::world::EntityType::Hoglin => Self::Hoglin,
            pumpkin_plugin_api::world::EntityType::HopperMinecart => Self::HopperMinecart,
            pumpkin_plugin_api::world::EntityType::Horse => Self::Horse,
            pumpkin_plugin_api::world::EntityType::Husk => Self::Husk,
            pumpkin_plugin_api::world::EntityType::Illusioner => Self::Illusioner,
            pumpkin_plugin_api::world::EntityType::Interaction => Self::Interaction,
            pumpkin_plugin_api::world::EntityType::IronGolem => Self::IronGolem,
            pumpkin_plugin_api::world::EntityType::Item => Self::Item,
            pumpkin_plugin_api::world::EntityType::ItemDisplay => Self::ItemDisplay,
            pumpkin_plugin_api::world::EntityType::ItemFrame => Self::ItemFrame,
            pumpkin_plugin_api::world::EntityType::JungleBoat => Self::JungleBoat,
            pumpkin_plugin_api::world::EntityType::JungleChestBoat => Self::JungleChestBoat,
            pumpkin_plugin_api::world::EntityType::LeashKnot => Self::LeashKnot,
            pumpkin_plugin_api::world::EntityType::LightningBolt => Self::LightningBolt,
            pumpkin_plugin_api::world::EntityType::LingeringPotion => Self::LingeringPotion,
            pumpkin_plugin_api::world::EntityType::Llama => Self::Llama,
            pumpkin_plugin_api::world::EntityType::LlamaSpit => Self::LlamaSpit,
            pumpkin_plugin_api::world::EntityType::MagmaCube => Self::MagmaCube,
            pumpkin_plugin_api::world::EntityType::MangroveBoat => Self::MangroveBoat,
            pumpkin_plugin_api::world::EntityType::MangroveChestBoat => Self::MangroveChestBoat,
            pumpkin_plugin_api::world::EntityType::Mannequin => Self::Mannequin,
            pumpkin_plugin_api::world::EntityType::Marker => Self::Marker,
            pumpkin_plugin_api::world::EntityType::Minecart => Self::Minecart,
            pumpkin_plugin_api::world::EntityType::Mooshroom => Self::Mooshroom,
            pumpkin_plugin_api::world::EntityType::Mule => Self::Mule,
            pumpkin_plugin_api::world::EntityType::Nautilus => Self::Nautilus,
            pumpkin_plugin_api::world::EntityType::OakBoat => Self::OakBoat,
            pumpkin_plugin_api::world::EntityType::OakChestBoat => Self::OakChestBoat,
            pumpkin_plugin_api::world::EntityType::Ocelot => Self::Ocelot,
            pumpkin_plugin_api::world::EntityType::OminousItemSpawner => Self::OminousItemSpawner,
            pumpkin_plugin_api::world::EntityType::Painting => Self::Painting,
            pumpkin_plugin_api::world::EntityType::PaleOakBoat => Self::PaleOakBoat,
            pumpkin_plugin_api::world::EntityType::PaleOakChestBoat => Self::PaleOakChestBoat,
            pumpkin_plugin_api::world::EntityType::Panda => Self::Panda,
            pumpkin_plugin_api::world::EntityType::Parched => Self::Parched,
            pumpkin_plugin_api::world::EntityType::Parrot => Self::Parrot,
            pumpkin_plugin_api::world::EntityType::Phantom => Self::Phantom,
            pumpkin_plugin_api::world::EntityType::Pig => Self::Pig,
            pumpkin_plugin_api::world::EntityType::Piglin => Self::Piglin,
            pumpkin_plugin_api::world::EntityType::PiglinBrute => Self::PiglinBrute,
            pumpkin_plugin_api::world::EntityType::Pillager => Self::Pillager,
            pumpkin_plugin_api::world::EntityType::Player => Self::Player,
            pumpkin_plugin_api::world::EntityType::PolarBear => Self::PolarBear,
            pumpkin_plugin_api::world::EntityType::Pufferfish => Self::Pufferfish,
            pumpkin_plugin_api::world::EntityType::Rabbit => Self::Rabbit,
            pumpkin_plugin_api::world::EntityType::Ravager => Self::Ravager,
            pumpkin_plugin_api::world::EntityType::Salmon => Self::Salmon,
            pumpkin_plugin_api::world::EntityType::Sheep => Self::Sheep,
            pumpkin_plugin_api::world::EntityType::Shulker => Self::Shulker,
            pumpkin_plugin_api::world::EntityType::ShulkerBullet => Self::ShulkerBullet,
            pumpkin_plugin_api::world::EntityType::Silverfish => Self::Silverfish,
            pumpkin_plugin_api::world::EntityType::Skeleton => Self::Skeleton,
            pumpkin_plugin_api::world::EntityType::SkeletonHorse => Self::SkeletonHorse,
            pumpkin_plugin_api::world::EntityType::Slime => Self::Slime,
            pumpkin_plugin_api::world::EntityType::SmallFireball => Self::SmallFireball,
            pumpkin_plugin_api::world::EntityType::Sniffer => Self::Sniffer,
            pumpkin_plugin_api::world::EntityType::Snowball => Self::Snowball,
            pumpkin_plugin_api::world::EntityType::SnowGolem => Self::SnowGolem,
            pumpkin_plugin_api::world::EntityType::SpawnerMinecart => Self::SpawnerMinecart,
            pumpkin_plugin_api::world::EntityType::SpectralArrow => Self::SpectralArrow,
            pumpkin_plugin_api::world::EntityType::Spider => Self::Spider,
            pumpkin_plugin_api::world::EntityType::SplashPotion => Self::SplashPotion,
            pumpkin_plugin_api::world::EntityType::SpruceBoat => Self::SpruceBoat,
            pumpkin_plugin_api::world::EntityType::SpruceChestBoat => Self::SpruceChestBoat,
            pumpkin_plugin_api::world::EntityType::Squid => Self::Squid,
            pumpkin_plugin_api::world::EntityType::Stray => Self::Stray,
            pumpkin_plugin_api::world::EntityType::Strider => Self::Strider,
            pumpkin_plugin_api::world::EntityType::Tadpole => Self::Tadpole,
            pumpkin_plugin_api::world::EntityType::TextDisplay => Self::TextDisplay,
            pumpkin_plugin_api::world::EntityType::Tnt => Self::Tnt,
            pumpkin_plugin_api::world::EntityType::TntMinecart => Self::TntMinecart,
            pumpkin_plugin_api::world::EntityType::TraderLlama => Self::TraderLlama,
            pumpkin_plugin_api::world::EntityType::Trident => Self::Trident,
            pumpkin_plugin_api::world::EntityType::TropicalFish => Self::TropicalFish,
            pumpkin_plugin_api::world::EntityType::Turtle => Self::Turtle,
            pumpkin_plugin_api::world::EntityType::Vex => Self::Vex,
            pumpkin_plugin_api::world::EntityType::Villager => Self::Villager,
            pumpkin_plugin_api::world::EntityType::Vindicator => Self::Vindicator,
            pumpkin_plugin_api::world::EntityType::WanderingTrader => Self::WanderingTrader,
            pumpkin_plugin_api::world::EntityType::Warden => Self::Warden,
            pumpkin_plugin_api::world::EntityType::WindCharge => Self::WindCharge,
            pumpkin_plugin_api::world::EntityType::Witch => Self::Witch,
            pumpkin_plugin_api::world::EntityType::Wither => Self::Wither,
            pumpkin_plugin_api::world::EntityType::WitherSkeleton => Self::WitherSkeleton,
            pumpkin_plugin_api::world::EntityType::WitherSkull => Self::WitherSkull,
            pumpkin_plugin_api::world::EntityType::Wolf => Self::Wolf,
            pumpkin_plugin_api::world::EntityType::Zoglin => Self::Zoglin,
            pumpkin_plugin_api::world::EntityType::Zombie => Self::Zombie,
            pumpkin_plugin_api::world::EntityType::ZombieHorse => Self::ZombieHorse,
            pumpkin_plugin_api::world::EntityType::ZombieNautilus => Self::ZombieNautilus,
            pumpkin_plugin_api::world::EntityType::ZombieVillager => Self::ZombieVillager,
            pumpkin_plugin_api::world::EntityType::ZombifiedPiglin => Self::ZombifiedPiglin,
            _ => Self::Zombie,
        }
    }
}

impl fmt::Display for EntityType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
